#!/bin/sh
#
########################################################################################
#
# 脚本为nagios的插件检测脚本，用于检测主机上串口服务器串口的状态:
#
#
#       ID       date           Name    Note
#       1       2014/05/23      CZZ     
#       NOTE:
#        
#
#       串口服务器一共16个口，传递的第二个参数为串口服务器的IP地址。
#
########################################################################################
#
NIC_NUM=16
UP_NUM=0
DOWN_NUM=0
MAIN_COUNT=1
IPADDRESS="$2"
if $(snmpwalk -v 2c -c public $IPADDRESS ifOperStatus > /dev/null 2>&1);then
	for num in $(snmpwalk -v 2c -c public $IPADDRESS ifOperStatus | cut -d" " -f4 |awk -F'(' '{print $1}' | tail -n 16)
	do
		if [ "$num" = 'up' ];then
	                SER_STATUS_UP[$UP_NUM]="${MAIN_COUNT}"
	                ((UP_NUM=$UP_NUM+1))
		else
	                SER_STATUS_DOWN[$DOWN_NUM]="${MAIN_COUNT}"
                	((DOWN_NUM=$DOWN_NUM+1))
        	fi
		((MAIN_COUNT=$MAIN_COUNT+1))

	done
	if [ ${#SER_STATUS_UP[@]} -eq 0 ];then
		echo "OK - 没有任何串口启用"
		exit 0
	else
		echo "OK - 串口 : ${SER_STATUS_UP[@]} :处于打开状态"
                exit 0
	fi
else
	echo "CRITICAL - 不能连接到串口服务器 $IPADDRESS "
        exit 2
fi
